global:
  scrape_interval: 15s # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    # This scrapes the Host Machine (Ubuntu) metrics
    static_configs:
      - targets: ['node-exporter:9100']